### ISSUE TITLE
distribute prebuild timeswipe npm module for arm 32 and 64

### ISSUE THREAD

**Issue by iluxa** [panda-official/TimeSwipe.js#1]

**Comment by IngoKaiser** [comment]
Have a look at this @iluxa:
https://github.com/orgs/panda-official/packages

wouldn't that make update easier?

**Comment by iluxa** [comment]
Hosting is not the issue
Issue is cross-compiling of binary python package, it requires some deps not available in cross-compile environment

**Comment by iluxa** [comment]
changes are pushed on master:
added script and Readme instructions on how to build and create new release
version changed to 0.0.6
new module pushed to npm
npm prebuild binaries are available for `armv7l` and `aarch64` archs for `v79` node version
it is possible to extend the building to different platforms and different node version

**Comment by IngoKaiser** [comment]
install is working. Will check on blank system later that day for final test.

**Comment by IngoKaiser** [comment]
@iluxa not working on timeswipeOS (10.0.0.2)

```
# npm install timeswipe

> deasync@0.1.19 install /root/nodejs/node_modules/deasync
> node ./build.js

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.14.95-v8
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nodejs/node_modules/deasync
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
Build failed
npm WARN nodejs@1.0.0 No description
npm WARN nodejs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.19 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.19 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-20T08_19_54_917Z-debug.log
```

**Comment by iluxa** [comment]
fixed in https://github.com/panda-official/TimeSwipe.js/commit/a63ea5b36c0c4e77e54f0032031518a5e5b28b91: removed dependency which required `make`

next release (0.0.7) should be installed properly on timeswipeOS

**Comment by iluxa** [comment]
checked on 0.0.8 on timeswipeOS

**Comment by IngoKaiser** [comment]
checked - got result:

```
# npm install timeswipe

> timeswipe@0.0.8 install /root/ingo/nodejs/node_modules/timeswipe
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
[timeswipe] Success: "/root/ingo/nodejs/node_modules/timeswipe/build/Release/obj.target/timeswipe.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nodejs@1.0.0 No description
npm WARN nodejs@1.0.0 No repository field.

+ timeswipe@0.0.8
added 72 packages from 77 contributors and audited 102 packages in 21.51s
found 0 vulnerabilities

# nano index.js
# node index.js
internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /root/ingo/nodejs/node_modules/timeswipe/build/Release/obj.target/timeswipe.node: wrong ELF class: ELFCLASS32
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/ingo/nodejs/node_modules/timeswipe/index.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
#
```

**Comment by IngoKaiser** [comment]
tested on 10.0.0.12 - /root/ingo/nodejs

**Comment by iluxa** [comment]
It works with `--update-binary` option on 10.0.0.12. Checking why it doesn't work without

**Comment by iluxa** [comment]
fixed in https://github.com/panda-official/TimeSwipe.js/commit/9edb9a180f8c69e070091e2379d0034fa03b9a16
tested `npm install timeswipe` on TimeSwipeOS - works fine

**Comment by IngoKaiser** [comment]
works
